channels:
- conda-forge
dependencies:
- python=3.8.18
- pip<=23.3.1
- pip:
  - mlflow==2.9.1
  - cffi==1.16.0
  - cloudpickle==3.0.0
  - defusedxml==0.7.1
  - gmpy2==2.1.2
  - numpy==1.24.3
  - packaging==23.2
  - pandas==2.0.3
  - pyyaml==6.0.1
  - requests==2.31.0
  - torch==2.1.1
  - torchvision==0.16.1
  - tqdm==4.66.1
name: mlflow-env
