services:
  iot_server_ms:
    build:
      context: .
      dockerfile: main.Dockerfile
    restart: unless-stopped
    container_name: iot_server_ms
    volumes:
      - ./log/:/app/log
    ports:
      - 5555:5555
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/status"]
      interval: 30s
      timeout: 10s
      retries: 5
    